### ISSUE TITLE
java.lang.ClassNotFoundException: org.restlet.ext.servlet.ServerServlet

### ISSUE THREAD

**Issue by nikhilbhalwankar** [Noterik/Rafael#3]
Hi,

I am getting below issue while running tomcat. What needs to be done? Looks like there are restlet jar file dependencies. What are the exact versions required?

java.lang.ClassNotFoundException: org.restlet.ext.servlet.ServerServlet
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1714)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1559)
	at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:527)
	at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:509)
	at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:137)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1144)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1088)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5176)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5460)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by pietervanleeuwen** [comment]
We had indeed some missing libraries for restlet that we on default did include in the tomcat libs folder.
With the [latest commit](https://github.com/Noterik/Rafael/commit/9bb7af01f2d3651c9557622328ff6265246c931e) this should be fixed.

**Comment by nikhilbhalwankar** [comment]
Thanks. The dependencies are now resolved. Server started ok.
